---
apiVersion: v1
kind: ConfigMap
metadata:
    name: core-reading-worker-config
    namespace: default
    labels:
        app: core-reading-worker
data:
    APP_ID: "Core.Reading.Worker-{BUILD_NUMBER}"
    BUILD_NUMBER: "{BUILD_NUMBER}"
    MQTT_URL: "mqtt://10.24.8.255"
    NODE_ENV: "production"
    PROJECT_ID: "production-282111"
    SERVICE_NAME: "Core.Reading.Worker"
    GCLOUD_CLIENT_EMAIL: "core-reader@production-282111.iam.gserviceaccount.com"
    GCLOUD_CLIENT_PRIVATE_KEY: "{GCLOUD_CLIENT_PRIVATE_KEY}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: core-reading-worker
    namespace: default
    labels:
        app: core-reading-worker
spec:
    replicas: 1
    selector:
        matchLabels:
            app: core-reading-worker
    template:
        metadata:
            labels:
                app: core-reading-worker
        spec:
            containers:
                -   name: core-reading-worker
                    image: gcr.io/production-282111/core-reading-worker:{BUILD_NUMBER}
                    env:
                        -   name: APP_ID
                            valueFrom:
                                configMapKeyRef:
                                    key: APP_ID
                                    name: core-reading-worker-config
                        -   name: BUILD_NUMBER
                            valueFrom:
                                configMapKeyRef:
                                    key: BUILD_NUMBER
                                    name: core-reading-worker-config
                        -   name: MQTT_URL
                            valueFrom:
                                configMapKeyRef:
                                    key: MQTT_URL
                                    name: core-reading-worker-config
                        -   name: NODE_ENV
                            valueFrom:
                                configMapKeyRef:
                                    key: NODE_ENV
                                    name: core-reading-worker-config
                        -   name: PROJECT_ID
                            valueFrom:
                                configMapKeyRef:
                                    key: PROJECT_ID
                                    name: core-reading-worker-config
                        -   name: SERVICE_NAME
                            valueFrom:
                                configMapKeyRef:
                                    key: SERVICE_NAME
                                    name: core-reading-worker-config
                        -   name: GCLOUD_CLIENT_EMAIL
                            valueFrom:
                                configMapKeyRef:
                                    key: GCLOUD_CLIENT_EMAIL
                                    name: core-reading-worker-config
                        -   name: GCLOUD_CLIENT_PRIVATE_KEY
                            valueFrom:
                                configMapKeyRef:
                                    key: GCLOUD_CLIENT_PRIVATE_KEY
                                    name: core-reading-worker-config
                    ports:
                        -   containerPort: 1883
                            protocol: TCP
                            name: mqtt
---
kind: Service
apiVersion: v1
metadata:
    name: core-reading-worker-discovery
spec:
    type: ClusterIP
    selector:
        app: core-reading-worker
    ports:
        -   protocol: TCP
            port: 1883
            targetPort: mqtt
